# CUDA_VISIBLE_DEVICES=0 python train.py --cfg configs/mpqa_train.yaml

LOG_DIR: 'logs'
METHOD: 'MPQA'
EXP_NAME: 'test'
RUN_TEST: False
SEED_VALUE: -1
PL_LOGGING: True
REFRESH_RATE: 5
FAST_DEV_RUN: False
DETECT_ANOMALY: False
DATASET:
  NOISE_FACTOR: 0.4
  ROT_FACTOR: 30
  BATCH_SIZE: 64
  NUM_WORKERS: 16
  PIN_MEMORY: False
  SHUFFLE_TRAIN: True
  TRAIN_DS: 'coco3d_h36m_inf'
  VAL_DS: '3dpw'
  NUM_IMAGES: -1
  IMG_RES: [224]
  FOCAL_LENGTH: 5000.
  MESH_COLOR: 'blue'
OPTIMIZER:
  TYPE: 'adam'
  LR: [0.00003]
  WD: [0.0]
TRAINING:
  RESUME: ''
  PRETRAINED: ''
  MAX_EPOCHS: 100
  LOG_SAVE_INTERVAL: 500
  LOG_FREQ_TB_IMAGES: 1000
  CHECK_VAL_EVERY_N_EPOCH: 5
  RELOAD_DATALOADERS_EVERY_N_EPOCH: 1
  SAVE_IMAGES: False
  USE_AUGM: True
  STRATEGY: 'ddp'
TESTING:
  SAVE_IMAGES: False
  SAVE_RESULTS: False
  LOG_FREQ_TB_IMAGES: 100
  SIDEVIEW: True
MPQA:
  # BACKBONE: ['resnet50']
  BACKBONE: ['hrnet_w32-conv']
  REGRESSOR: ['mpqa']
  CRITERION: ['NIoULoss']
  SURFACE_LOSS_WEIGHT: 1.
  SHAPE_LOSS_WEIGHT: 0.
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
  GAMMA_VAL: [1.0e-4]
  SIGMA_VAL: [1.0e-1]
  RENDER_MASK: 6
  USE_PRETREATMENT: False
  PRETREATMENT_FILTER: [[1024,]]
  PRETREATMENT_KERNEL: [[1,]]
  VIT_PATCH: 4
  VIT_FILTER: [[768, 768, 768]]
  USE_POS_EMBED: True
  USE_MAE_MASK: False
  MAE_MASK_RATIO: 0.